### ISSUE TITLE
loginInfo module error

### ISSUE THREAD

**Issue by torlakfaruk** [hikaruAi/FacebookBot#1]
There is no module named loginInfo and it's not run becouse of that.
Error:
ImportError: No module named 'loginInfo'

What should i do for it

**Comment by Giando** [comment]
@torlakfaruk same problem.

Thanks @hikaruAi!

**Comment by luckyankit** [comment]
yes. same issue still exists

**Comment by quintendewilde** [comment]
what's the solution?
